export interface RoleDefinition {
  id: string;
  name: string;
  category: "Engineering" | "Data & AI" | "Security & Ops" | "Product & Design";
  description: string;
  coreSkillKeywords: string[];
  relevantSkillKeywords?: string[];
  evidenceFocus: string[];
}

export const TARGET_ROLES: RoleDefinition[] = [
  {
    id: "frontend-engineer",
    name: "Frontend Engineer",
    category: "Engineering",
    description: "Builds high-performance, responsive user interfaces and client-side web applications.",
    coreSkillKeywords: [
      "react",
      "next.js",
      "vue",
      "angular",
      "svelte",
      "typescript",
      "javascript",
      "html5",
      "html",
      "css3",
      "css",
      "tailwind css",
      "redux",
      "zustand",
      "webpack",
      "vite",
      "ui/ux design",
      "framer-motion",
    ],
    relevantSkillKeywords: [
      "node.js",
      "rest api",
      "graphql",
      "git",
      "jest",
      "vitest",
      "cypress",
      "ci/cd",
      "docker",
      "web accessibility",
      "performance optimization",
    ],
    evidenceFocus: ["Frontend components", "UI styling", "State management", "Client build configs", "Unit/Component tests"],
  },
  {
    id: "backend-engineer",
    name: "Backend Engineer",
    category: "Engineering",
    description: "Architects scalable APIs, microservices, databases, and server-side business logic.",
    coreSkillKeywords: [
      "node.js",
      "express",
      "nestjs",
      "python",
      "django",
      "fastapi",
      "flask",
      "java",
      "spring boot",
      "go",
      "rust",
      "postgresql",
      "mysql",
      "mongodb",
      "redis",
      "prisma",
      "graphql",
      "rest api",
      "docker",
      "system design",
      "sql",
    ],
    relevantSkillKeywords: [
      "typescript",
      "javascript",
      "kubernetes",
      "ci/cd",
      "git",
      "aws",
      "gcp",
      "linux",
      "microservices",
      "kafka",
      "rabbitmq",
      "pytest",
      "jest",
    ],
    evidenceFocus: ["API endpoints", "Database schemas & migrations", "Server architectures", "Integration tests", "Docker configurations"],
  },
  {
    id: "fullstack-engineer",
    name: "Full Stack Engineer",
    category: "Engineering",
    description: "Designs and delivers end-to-end applications spanning client interfaces, backend servers, and databases.",
    coreSkillKeywords: [
      "react",
      "next.js",
      "typescript",
      "javascript",
      "node.js",
      "express",
      "python",
      "postgresql",
      "mongodb",
      "prisma",
      "rest api",
      "graphql",
      "docker",
      "ci/cd",
      "git",
      "tailwind css",
      "sql",
    ],
    relevantSkillKeywords: [
      "vue",
      "angular",
      "redis",
      "aws",
      "gcp",
      "kubernetes",
      "jest",
      "vitest",
      "cypress",
      "fastapi",
      "django",
      "system design",
    ],
    evidenceFocus: ["Full-stack repositories", "Client-server integration", "Database operations", "CI workflows", "End-to-end tests"],
  },
  {
    id: "mobile-engineer",
    name: "Mobile Engineer",
    category: "Engineering",
    description: "Develops native or cross-platform mobile apps for iOS and Android devices.",
    coreSkillKeywords: [
      "react native",
      "flutter",
      "swift",
      "kotlin",
      "objective-c",
      "dart",
      "ios",
      "android",
      "mobile ui",
      "expo",
    ],
    relevantSkillKeywords: [
      "typescript",
      "javascript",
      "rest api",
      "graphql",
      "git",
      "redux",
      "sqlite",
      "firebase",
      "ci/cd",
    ],
    evidenceFocus: ["Mobile project structures", "Native modules", "App manifests", "Mobile UI components"],
  },
  {
    id: "devops-engineer",
    name: "DevOps & Cloud Engineer",
    category: "Security & Ops",
    description: "Automates CI/CD pipelines, container orchestration, cloud infrastructure, and observability.",
    coreSkillKeywords: [
      "docker",
      "kubernetes",
      "ci/cd",
      "github actions",
      "terraform",
      "aws",
      "gcp",
      "azure",
      "linux",
      "shell",
      "bash",
      "helm",
      "prometheus",
      "grafana",
    ],
    relevantSkillKeywords: [
      "python",
      "go",
      "git",
      "ansible",
      "nginx",
      "security",
      "networking",
      "microservices",
    ],
    evidenceFocus: ["CI/CD workflow YAMLs", "Dockerfiles / compose", "Terraform / IaC configs", "Deployment automation"],
  },
  {
    id: "data-scientist",
    name: "Data Scientist & ML Engineer",
    category: "Data & AI",
    description: "Builds predictive models, data processing pipelines, machine learning models, and analytical tools.",
    coreSkillKeywords: [
      "python",
      "tensorflow",
      "pytorch",
      "pandas",
      "numpy",
      "scikit-learn",
      "r",
      "sql",
      "jupyter notebook",
      "data analysis",
      "deep learning",
      "machine learning",
      "nlp",
      "computer vision",
    ],
    relevantSkillKeywords: [
      "docker",
      "git",
      "postgresql",
      "fastapi",
      "flask",
      "spark",
      "airflow",
      "aws",
      "gcp",
    ],
    evidenceFocus: ["Jupyter notebooks", "Data pipeline scripts", "Model definitions", "Scientific computing libraries"],
  },
  {
    id: "cybersecurity-analyst",
    name: "Cybersecurity Analyst",
    category: "Security & Ops",
    description: "Assesses security vulnerabilities, implements secure coding practices, and audits application defenses.",
    coreSkillKeywords: [
      "cybersecurity",
      "network security",
      "linux",
      "python",
      "cryptography",
      "penetration testing",
      "security auditing",
      "owasp",
      "wireshark",
      "auth",
    ],
    relevantSkillKeywords: [
      "bash",
      "shell",
      "docker",
      "ci/cd",
      "git",
      "siem",
      "burp suite",
      "vulnerability assessment",
    ],
    evidenceFocus: ["Security configurations", "Authentication implementations", "Audit configs", "Security scripts"],
  },
];
